allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': set this to true or false
  es5-ext: true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - sharp
