# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Local Config
version: 1.0.0
models:
  - name: Qwen 3.8
    provider: ollama
    model: qwen3.8
    apiBase: http://localhost:11434

tabAutocompleteModel:
  name: Qwen Autocomplete
  provider: ollama
  model: qwen3.8
  apiBase: http://localhost:11434